"""Summarise SkillNode verification runs: per scenario, per verb, per policy path.

    python tools/verify_summary.py                                   # print
    python tools/verify_summary.py --write                           # also write skill_library/verification/STATUS.md + status.json

A verb counts as verified when at least one call of it, top-level or nested in a
multi-object Contract, passed all of its GT pre- and postconditions in Isaac Sim.
"""
from __future__ import annotations

import argparse
import json
from pathlib import Path
import sys

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT))


def collect(root):
    return [json.loads(f.read_text()) for f in sorted(Path(root).glob("*/result.json"))]


def walk(step, scenario, out):
    out.append((scenario, step))
    for child in step.get("children", []):
        walk(child, scenario, out)


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--root", default=str(ROOT / "runs/skillv2/verify"))
    ap.add_argument("--write", action="store_true")
    args = ap.parse_args()
    from skill_library.graph import load_skills
    skills = sorted(load_skills().values(), key=lambda s: s["skill_id"])
    verbs = {s["verb"]: s for s in skills}
    rows = collect(args.root)
    calls = []
    lines = []
    for r in rows:
        last = r["steps"][-1] if r["steps"] else None
        ok = r["success"]
        msg = "" if ok else (r.get("crash") or (last and f"step {last['index']} {last['action']}: {last['error']}"))
        lines.append((r["id"], ok, f"{len([s for s in r['steps'] if s['success']])}/{len(r['steps'])}", msg or ""))
        for s in r["steps"]:
            walk({"action": s["action"], "success": s["success"], "path": s["path"], "error": s["error"],
                  "postconditions": s.get("postconditions", []), "children": s.get("children", []),
                  "skill": s["skill"]}, r["id"], calls)
    passed, failed, paths = {}, {}, {}
    for scenario, c in calls:
        verb = c.get("skill") or next((v for v in verbs if c["action"].startswith(v + "_")), None)
        if verb is None:
            continue
        if c["success"]:
            passed.setdefault(verb, []).append((scenario, c))
            paths.setdefault(verb, set()).add(c["path"])
        else:
            failed.setdefault(verb, []).append((scenario, c))
    for sid, ok, n, msg in lines:
        print(f"{'PASS' if ok else 'FAIL'} {sid:<18} {n:<6} {msg[:200]}")
    print(f"\nverbs passed: {len(passed)}/{len(verbs)}; missing: {sorted(set(verbs) - set(passed))}")
    n_paths = sum(len(s["policy_paths"]) for s in skills)
    n_passed_paths = sum(len(v) for v in paths.values())
    print(f"policy paths passed: {n_passed_paths}/{n_paths}")
    if not args.write:
        return
    out = ROOT / "skill_library/verification"
    status = {"scenarios": [{"id": i, "success": ok, "steps": n, "failure": m} for i, ok, n, m in lines],
              "verbs": {}}
    L = ["# SkillNode physical verification", "",
         "Generated by `tools/verify_summary.py --write` from Isaac Sim runs of "
         "[scenarios.json](scenarios.json) (`tools/verify_skills.py --all`). A verb is verified when at least one "
         "call passed every GT precondition and postcondition; nested calls inside multi-object Contracts count.", "",
         f"**{len(passed)}/{len(verbs)} verbs verified**, {n_passed_paths}/{n_paths} noun-selected policy paths "
         f"exercised; {sum(1 for _, ok, _, _ in lines if ok)}/{len(lines)} scenarios passed end to end.", "",
         "| SkillNode | Verb | Status | Paths passed | Evidence (scenario: measured postconditions) |", "|---|---|---|---|---|"]
    for s in skills:
        v = s["verb"]
        if v in passed:
            sc, c = passed[v][0]
            post = "; ".join(f"`{p['atom']}` {p['detail']}" for p in c["postconditions"][:2])
            ev = f"{sc}: {post}"[:300]
            st = "verified"
        else:
            sc, c = (failed.get(v) or [(None, None)])[0]
            ev = f"{sc}: {c['error']}"[:300] if c else "not run"
            st = "failed" if c else "not run"
        all_paths = [p["path_id"] for p in s["policy_paths"]]
        done = sorted(paths.get(v, set()))
        L.append(f"| `{s['skill_id']}` | {v} | {st} | {', '.join(done) or '-'} / {len(all_paths)} | "
                 f"{ev.replace('|', '/')} |")
        status["verbs"][v] = {"status": st, "paths_passed": done, "paths": all_paths, "evidence": ev}
    L += ["", "## Scenarios", "", "| Scenario | Result | Steps | Failure |", "|---|---|---|---|"]
    L += [f"| {i} | {'pass' if ok else 'fail'} | {n} | {(m or '').replace('|', '/')[:250]} |" for i, ok, n, m in lines]
    (out / "STATUS.md").write_text("\n".join(L) + "\n")
    readme = ROOT / "README.md"
    text = readme.read_text()
    a, b = "<!-- verification:start -->", "<!-- verification:end -->"
    block = (f"**物理验证**（Isaac Sim，GT 前后条件全部测量通过才计）：{len(passed)}/{len(verbs)} 个动词、"
             f"{n_passed_paths}/{n_paths} 条 policy 路径已通过，{sum(1 for _, ok, _, _ in lines if ok)}/{len(lines)} "
             "个验证场景端到端通过。逐动词证据与失败原因见 "
             "[verification/STATUS.md](skill_library/verification/STATUS.md)。")
    i, j = text.index(a), text.index(b)
    readme.write_text(text[:i + len(a)] + "\n" + block + "\n" + text[j:])
    (out / "status.json").write_text(json.dumps(status, indent=1) + "\n")
    print("WROTE", out / "STATUS.md")


if __name__ == "__main__":
    main()
